fix(deps): update ktor monorepo to v2.3.13 (#4619)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[io.ktor:ktor-server-test-host](https://redirect.github.com/ktorio/ktor)
| `2.3.9` -> `2.3.13` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-test-host/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-test-host/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-test-host/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-test-host/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-server-core](https://redirect.github.com/ktorio/ktor) |
`2.3.9` -> `2.3.13` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-core/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-core/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-core/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-core/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-apache](https://redirect.github.com/ktorio/ktor)
| `2.3.9` -> `2.3.13` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-apache/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-apache/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-apache/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-apache/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-js](https://redirect.github.com/ktorio/ktor) |
`2.3.9` -> `2.3.13` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-js/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-js/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-js/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-js/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-core](https://redirect.github.com/ktorio/ktor) |
`2.3.9` -> `2.3.13` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-core/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-core/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-core/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-core/2.3.9/2.3.13?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>ktorio/ktor (io.ktor:ktor-server-test-host)</summary>

###
[`v2.3.13`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#2313)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/2.3.12...2.3.13)

> Published 20 November 2024

##### Bugfixes

- CIO: Requests face connection timeouts when executed on the Android
main dispatcher
([KTOR-6803](https://youtrack.jetbrains.com/issue/KTOR-6803))
- io.ktor.util.TextKt.chomp doesn't work on strings with more than one
character ([KTOR-7209](https://youtrack.jetbrains.com/issue/KTOR-7209))
- "java.lang.IllegalArgumentException: Failed requirement." in
SelectorManagerSupport
([KTOR-2914](https://youtrack.jetbrains.com/issue/KTOR-2914))
- Backport fix for CVE-2024-49580 to Ktor 2
([KTOR-7727](https://youtrack.jetbrains.com/issue/KTOR-7727))

##### Improvements

- Replace custom withTimeout implementation using WeakTimeoutQueue with
coroutines.withTimeout
([KTOR-3658](https://youtrack.jetbrains.com/issue/KTOR-3658))
- Add watchosDeviceArm64 target
([KTOR-6368](https://youtrack.jetbrains.com/issue/KTOR-6368))

###
[`v2.3.12`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#2312)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/2.3.11...2.3.12)

> Published 20 June 2024

##### Bugfixes

- NoSuchMethodError when using coroutines 1.9.0-RC
([KTOR-7054](https://youtrack.jetbrains.com/issue/KTOR-7054))
- Server: Content-Type header for static js, css and svg resources
misses charset
([KTOR-6655](https://youtrack.jetbrains.com/issue/KTOR-6655))
- Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network
([KTOR-7016](https://youtrack.jetbrains.com/issue/KTOR-7016))

##### Improvements

- Update netty to 4.1.111.Final
([KTOR-7094](https://youtrack.jetbrains.com/issue/KTOR-7094))
- Update netty due to CVE-2024-29025
([KTOR-7014](https://youtrack.jetbrains.com/issue/KTOR-7014))
- Update dependency on swagger
([KTOR-7019](https://youtrack.jetbrains.com/issue/KTOR-7019))

###
[`v2.3.11`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#2311)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/2.3.10...2.3.11)

> Published 8 May 2024

##### Bugfixes

- Test client ignores socket timeout
([KTOR-6909](https://youtrack.jetbrains.com/issue/KTOR-6909))

###
[`v2.3.10`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#2310)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/2.3.9...2.3.10)

> Published 8 April 2024

##### Bugfixes

- CallLogging, StatusPages: response logged twice when status handler is
used ([KTOR-6839](https://youtrack.jetbrains.com/issue/KTOR-6839))
- NodeJS WebSocket client sometimes drops a frame received immediately
after handshake
([KTOR-6883](https://youtrack.jetbrains.com/issue/KTOR-6883))
- IPv6 addresses are not supported in NettyConnectionPoint and
CIOConnectionPoint
([KTOR-5383](https://youtrack.jetbrains.com/issue/KTOR-5383))
- JS browser: "Maximum call stack size exceeded" on HTTP request when
targeting es2015
([KTOR-6878](https://youtrack.jetbrains.com/issue/KTOR-6878))
- CIO: File upload fails with `NumberFormatException` when uploading
file larger than INT_MAX bytes (~2.1 GiB) since 2.3.0
([KTOR-6851](https://youtrack.jetbrains.com/issue/KTOR-6851))
- CallLogging: the plugin completely overrides MDC if at least one entry
is configured
([KTOR-6642](https://youtrack.jetbrains.com/issue/KTOR-6642))
- SSE plugin: Duplicated "Content-Type: text/event-stream" headers
([KTOR-6735](https://youtrack.jetbrains.com/issue/KTOR-6735))
- CIO: "getSubjectAlternativeNames(...) must not be null" when
IP-addresses are verified and no SAN in the certificate
([KTOR-6746](https://youtrack.jetbrains.com/issue/KTOR-6746))

##### Improvements

- Inconsistent behavior of Netty and rest engines by returning null or
empty string for query parameters without values
([KTOR-6850](https://youtrack.jetbrains.com/issue/KTOR-6850))
- Android: no logs are present in Logcat with `Logger.ANDROID`
([KTOR-1219](https://youtrack.jetbrains.com/issue/KTOR-1219))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on the first day of the
month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/kotest/kotest).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS44NS4wIiwidXBkYXRlZEluVmVyIjoiMzkuODUuMCIsInRhcmdldEJyYW5jaCI6Im1hc3RlciIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>