Handle nested and quoted paths in JSON key navigation (#5699)
This fixes `shouldNotContainJsonKey` for when it fails and throws an
unhelpful exception.

```kotlin
it.shouldNotContainJsonKey("$.validation_constraints['layout_items[0].url']")
```
Would just throw this:
```
Property has not been closed - missing closing '
com.jayway.jsonpath.InvalidPathException: Property has not been closed - missing closing '
	at com.jayway.jsonpath.internal.path.PathCompiler.fail(PathCompiler.java:642)
	at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:625)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:137)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:256)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:153)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:175)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:143)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:123)

```

Co-authored-by: Alex Kuznetsov <Alex.Cue.987@gmail.com>
Co-authored-by: Sam <sam@sksamuel.com>