fix(deps): update dependency org.springframework.boot:spring-boot-starter-test to v2.7.18 (#4618)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[org.springframework.boot:spring-boot-starter-test](https://spring.io/projects/spring-boot)
([source](https://redirect.github.com/spring-projects/spring-boot)) |
`2.7.16` -> `2.7.18` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-starter-test/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework.boot:spring-boot-starter-test/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework.boot:spring-boot-starter-test/2.7.16/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-starter-test/2.7.16/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>spring-projects/spring-boot
(org.springframework.boot:spring-boot-starter-test)</summary>

###
[`v2.7.18`](https://redirect.github.com/spring-projects/spring-boot/releases/tag/v2.7.18)

[Compare
Source](https://redirect.github.com/spring-projects/spring-boot/compare/v2.7.17...v2.7.18)

#### ⚠️ Noteworthy Changes

- Following the Paketo team's
[announcement](https://blog.paketo.io/posts/paketo-bionic-builder-is-unsafe/)
that the Bionic CNB builders will be removed, the default builder using
by `bootBuildImage` (Gradle) and `spring-boot:build-image` (Maven) has
been changed to Paketo Jammy
[#&#8203;38477](https://redirect.github.com/spring-projects/spring-boot/issues/38477)

#### :lady_beetle: Bug Fixes

- App fails to start with a NoSuchMethodError when using Flyway 10.0.0
[#&#8203;38164](https://redirect.github.com/spring-projects/spring-boot/issues/38164)
- spring.webflux.multipart.max-disk-usage-per-part behaves incorrectly
for values where the number of bytes overflows an int
[#&#8203;38146](https://redirect.github.com/spring-projects/spring-boot/issues/38146)
- Mail health indicator fails when host is not set in properties
[#&#8203;38007](https://redirect.github.com/spring-projects/spring-boot/issues/38007)

#### :notebook_with_decorative_cover: Documentation

- Document supported SQL comment prefixes
[#&#8203;38385](https://redirect.github.com/spring-projects/spring-boot/pull/38385)
- Fix link to Elasticsearch health indicator
[#&#8203;38330](https://redirect.github.com/spring-projects/spring-boot/pull/38330)
- Improve --help and documentation for "encodepassword -a/--algorithm"
in the Spring Boot CLI
[#&#8203;38203](https://redirect.github.com/spring-projects/spring-boot/issues/38203)
- Document that TomcatConnectorCustomizers are not applied to additional
connectors
[#&#8203;38183](https://redirect.github.com/spring-projects/spring-boot/issues/38183)
- MyErrorWebExceptionHandler example in documentation isn't working
[#&#8203;38104](https://redirect.github.com/spring-projects/spring-boot/issues/38104)
- Document that SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS is
disabled by default
[#&#8203;38083](https://redirect.github.com/spring-projects/spring-boot/issues/38083)
- Update "Running Behind a Front-end Proxy Server" to include reactive
and ForwardedHeaderTransformer
[#&#8203;37282](https://redirect.github.com/spring-projects/spring-boot/issues/37282)
- Improve documentation of `classpath.idx` file and its generation by
the Maven and Gradle plugins
[#&#8203;37125](https://redirect.github.com/spring-projects/spring-boot/issues/37125)
- Document configuration for building images with Colima
[#&#8203;34522](https://redirect.github.com/spring-projects/spring-boot/issues/34522)
- Code sample in "Developing Your First Spring Boot Application" does
not work
[#&#8203;34513](https://redirect.github.com/spring-projects/spring-boot/issues/34513)
- Document ConfigurationPropertyCaching
[#&#8203;34172](https://redirect.github.com/spring-projects/spring-boot/issues/34172)
- Document that application.\* banner variables require a packaged jar
or the use of Boot's launcher
[#&#8203;33489](https://redirect.github.com/spring-projects/spring-boot/issues/33489)
- Add section on AspectJ support
[#&#8203;32642](https://redirect.github.com/spring-projects/spring-boot/issues/32642)
- Document server.servlet.encoding.\* properties and
server.servlet.encoding.mapping in particular
[#&#8203;32472](https://redirect.github.com/spring-projects/spring-boot/issues/32472)
- Add a section on customizing embedded reactive servers
[#&#8203;31917](https://redirect.github.com/spring-projects/spring-boot/issues/31917)
- Clarify that MVC components provided through WebMvcRegistrations are
subject to subsequent processing and configuration by MVC
[#&#8203;31232](https://redirect.github.com/spring-projects/spring-boot/issues/31232)
- Clarifying documentation on including a top-level `@TestConfiguration`
class in a test
[#&#8203;30513](https://redirect.github.com/spring-projects/spring-boot/issues/30513)
- Clarify that `@AutoConfigureWebTestClient` binds WebTestClient to mock
infrastructure
[#&#8203;29890](https://redirect.github.com/spring-projects/spring-boot/issues/29890)
- Improve systemd configuration documentation
[#&#8203;28453](https://redirect.github.com/spring-projects/spring-boot/issues/28453)
- Document how to customize the basePackages that auto-configurations
consider (for example Spring Data Repositories)
[#&#8203;27549](https://redirect.github.com/spring-projects/spring-boot/issues/27549)
- Document additional user configuration that's required after setting
`spring.hateoas.use-hal-as-default-json-media-type` to `false`
[#&#8203;26814](https://redirect.github.com/spring-projects/spring-boot/issues/26814)
- Add how-to documentation for test-only database migrations with
Flyway/Liquibase
[#&#8203;26796](https://redirect.github.com/spring-projects/spring-boot/issues/26796)

#### :hammer: Dependency Upgrades

- Upgrade to ActiveMQ 5.16.7
[#&#8203;38427](https://redirect.github.com/spring-projects/spring-boot/issues/38427)
- Upgrade to DB2 JDBC 11.5.9.0
[#&#8203;38428](https://redirect.github.com/spring-projects/spring-boot/issues/38428)
- Upgrade to Dropwizard Metrics 4.2.22
[#&#8203;38429](https://redirect.github.com/spring-projects/spring-boot/issues/38429)
- Upgrade to Elasticsearch 7.17.15
[#&#8203;38430](https://redirect.github.com/spring-projects/spring-boot/issues/38430)
- Upgrade to Glassfish JAXB 2.3.9
[#&#8203;38431](https://redirect.github.com/spring-projects/spring-boot/issues/38431)
- Upgrade to Micrometer 1.9.17
[#&#8203;38279](https://redirect.github.com/spring-projects/spring-boot/issues/38279)
- Upgrade to Netty 4.1.101.Final
[#&#8203;38432](https://redirect.github.com/spring-projects/spring-boot/issues/38432)
- Upgrade to Pooled JMS 1.2.6
[#&#8203;38433](https://redirect.github.com/spring-projects/spring-boot/issues/38433)
- Upgrade to Reactor Bom 2020.0.38
[#&#8203;38280](https://redirect.github.com/spring-projects/spring-boot/issues/38280)
- Upgrade to Spring Batch 4.3.10
[#&#8203;38281](https://redirect.github.com/spring-projects/spring-boot/issues/38281)
- Upgrade to Spring Data Bom 2021.2.18
[#&#8203;38282](https://redirect.github.com/spring-projects/spring-boot/issues/38282)
- Upgrade to Spring Framework 5.3.31
[#&#8203;38283](https://redirect.github.com/spring-projects/spring-boot/issues/38283)
- Upgrade to Spring HATEOAS 1.5.6
[#&#8203;38373](https://redirect.github.com/spring-projects/spring-boot/issues/38373)
- Upgrade to Spring Integration 5.5.20
[#&#8203;38491](https://redirect.github.com/spring-projects/spring-boot/issues/38491)
- Upgrade to Spring RESTDocs 2.0.8.RELEASE
[#&#8203;38434](https://redirect.github.com/spring-projects/spring-boot/issues/38434)
- Upgrade to Spring WS 3.1.8
[#&#8203;38284](https://redirect.github.com/spring-projects/spring-boot/issues/38284)
- Upgrade to Tomcat 9.0.83
[#&#8203;38435](https://redirect.github.com/spring-projects/spring-boot/issues/38435)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;GVictorG7](https://redirect.github.com/GVictorG7),
[@&#8203;PENEKhun](https://redirect.github.com/PENEKhun),
[@&#8203;dreis2211](https://redirect.github.com/dreis2211), and
[@&#8203;izeye](https://redirect.github.com/izeye)

###
[`v2.7.17`](https://redirect.github.com/spring-projects/spring-boot/releases/tag/v2.7.17)

[Compare
Source](https://redirect.github.com/spring-projects/spring-boot/compare/v2.7.16...v2.7.17)

#### :warning: Noteworthy Changes

- The behavior of `spring.jms.listener.concurrency` has been corrected
to match the documentation
([#&#8203;37180](https://redirect.github.com/spring-projects/spring-boot/pull/37180)).
If you were setting `spring.jms.listener.concurrency` without also
setting `spring.jms.listener.max-concurrency`, please review your
configuration when upgrading.

#### :lady_beetle: Bug Fixes

- `@Order` does not work on (CommandLine|Application)Runner `@Bean`
methods
[#&#8203;37905](https://redirect.github.com/spring-projects/spring-boot/pull/37905)
- Gradle plugin uses to-be-deprecated API for getting and setting file
permissions
[#&#8203;37878](https://redirect.github.com/spring-projects/spring-boot/issues/37878)
- Task executor metrics are not registered when using lazy
initialization
[#&#8203;37832](https://redirect.github.com/spring-projects/spring-boot/issues/37832)
- Constructor binding with a custom collection type does not work
[#&#8203;37734](https://redirect.github.com/spring-projects/spring-boot/issues/37734)
- Dependency management for kafka-server-common with a test classifier
is missing
[#&#8203;37499](https://redirect.github.com/spring-projects/spring-boot/issues/37499)
- fileMode and dirMode are not applied to all entries in an archive
produced by BootJar
[#&#8203;37496](https://redirect.github.com/spring-projects/spring-boot/issues/37496)
- Gradle plugin's build info support produces a deprecation warning when
using Gradle 8.4-rc-1
[#&#8203;37493](https://redirect.github.com/spring-projects/spring-boot/issues/37493)
- RepackageMojo doesn't support 1 digit numerical values for
project.build.outputTimestamp
[#&#8203;37438](https://redirect.github.com/spring-projects/spring-boot/pull/37438)
- Restarter creates memory leak in tests
[#&#8203;37373](https://redirect.github.com/spring-projects/spring-boot/issues/37373)
- Contrary to the documentation, setting spring.jms.listener.concurrency
alone configures the maximum concurrency
[#&#8203;37180](https://redirect.github.com/spring-projects/spring-boot/pull/37180)
- Application fails to start when an optional config import cannot be
resolved
[#&#8203;35683](https://redirect.github.com/spring-projects/spring-boot/issues/35683)
- `@ComponentScan` on a test class is processed when creating a test
context but is not included in the context's cache key
[#&#8203;31577](https://redirect.github.com/spring-projects/spring-boot/issues/31577)
- AspectJ transaction management with compile-time weaving does not work
with spring.main.lazy-initialization=true
[#&#8203;37506](https://redirect.github.com/spring-projects/spring-boot/issues/37506)

#### :notebook_with_decorative_cover: Documentation

- Remove link to LiveReload website due to timeout
[#&#8203;37643](https://redirect.github.com/spring-projects/spring-boot/pull/37643)
- Refer to ActiveMQ as ActiveMQ "Classic"
[#&#8203;37606](https://redirect.github.com/spring-projects/spring-boot/pull/37606)
- Use more idiomatic Kotlin in example for "Map Health Indicators to
Micrometer Metrics"
[#&#8203;37491](https://redirect.github.com/spring-projects/spring-boot/pull/37491)
- Document support for Java 21
[#&#8203;37371](https://redirect.github.com/spring-projects/spring-boot/issues/37371)

#### :hammer: Dependency Upgrades

- Upgrade to Dropwizard Metrics 4.2.21
[#&#8203;37893](https://redirect.github.com/spring-projects/spring-boot/issues/37893)
- Upgrade to Elasticsearch 7.17.14
[#&#8203;37840](https://redirect.github.com/spring-projects/spring-boot/issues/37840)
- Upgrade to Infinispan 13.0.20.Final
[#&#8203;37841](https://redirect.github.com/spring-projects/spring-boot/issues/37841)
- Upgrade to Jetty 9.4.53.v20231009
[#&#8203;37842](https://redirect.github.com/spring-projects/spring-boot/issues/37842)
- Upgrade to Jetty Reactive HTTPClient 1.1.15
[#&#8203;37927](https://redirect.github.com/spring-projects/spring-boot/issues/37927)
- Upgrade to Micrometer 1.9.16
[#&#8203;37674](https://redirect.github.com/spring-projects/spring-boot/issues/37674)
- Upgrade to Netty 4.1.100.Final
[#&#8203;37843](https://redirect.github.com/spring-projects/spring-boot/issues/37843)
- Upgrade to Pooled JMS 1.2.5
[#&#8203;37894](https://redirect.github.com/spring-projects/spring-boot/issues/37894)
- Upgrade to Reactor Bom 2020.0.37
[#&#8203;37675](https://redirect.github.com/spring-projects/spring-boot/issues/37675)
- Upgrade to Spring AMQP 2.4.17
[#&#8203;37676](https://redirect.github.com/spring-projects/spring-boot/issues/37676)
- Upgrade to Spring Data Bom 2021.2.17
[#&#8203;37677](https://redirect.github.com/spring-projects/spring-boot/issues/37677)
- Upgrade to Spring Session Bom 2021.2.3
[#&#8203;37928](https://redirect.github.com/spring-projects/spring-boot/issues/37928)
- Upgrade to Tomcat 9.0.82
[#&#8203;37895](https://redirect.github.com/spring-projects/spring-boot/issues/37895)
- Upgrade to UnboundID LDAPSDK 6.0.10
[#&#8203;37753](https://redirect.github.com/spring-projects/spring-boot/issues/37753)
- Upgrade to Undertow 2.2.28.Final
[#&#8203;37929](https://redirect.github.com/spring-projects/spring-boot/issues/37929)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:


[@&#8203;bottlerocketjonny](https://redirect.github.com/bottlerocketjonny),
[@&#8203;dependabot](https://redirect.github.com/dependabot)\[bot],
[@&#8203;erichaagdev](https://redirect.github.com/erichaagdev),
[@&#8203;esperar](https://redirect.github.com/esperar),
[@&#8203;izeye](https://redirect.github.com/izeye),
[@&#8203;jbertram](https://redirect.github.com/jbertram),
[@&#8203;nielsbasjes](https://redirect.github.com/nielsbasjes),
[@&#8203;onobc](https://redirect.github.com/onobc),
[@&#8203;ttddyy](https://redirect.github.com/ttddyy), and
[@&#8203;vpavic](https://redirect.github.com/vpavic)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on the first day of the
month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/kotest/kotest).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS44NS4wIiwidXBkYXRlZEluVmVyIjoiMzkuODUuMCIsInRhcmdldEJyYW5jaCI6Im1hc3RlciIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>